### ISSUE TITLE
Suggestion: Set default printWidth higher

### ISSUE THREAD

**Issue by pmdevita** [idleberg/sveltekit-adapter-html-like#3]
### Description

By default, without a user specified Prettier config, Prettier is set to use a max `printWidth` setting of 100. This can cause issues with how it tries to place line breaks, as it may place them inside template tags and break them. We should probably set this default higher so developers don't accidentally run into it.

In general, since we are rendering templates rather than pure HTML, it might be a good idea to have an option to disable Prettier since it may not be suitable for some template types.

### Steps to Reproduce

1. Create a 100+ character line of template tags
2. Prettier inserts a line break, potentially breaking a template tag.

**Expected behavior:**

Prettier leaves the line as-is.

**Actual behavior:**

Prettier inserts a line break and breaks one of the template tags.

**Reproduces how often:**

100% depending on your template language and how its tags work.

**Comment by idleberg** [comment]
To be honest, I don't even remember why it uses 120 (not 100) at this point. I'd rather go with Prettier's default values, even though it's lower. Personally, I'm not a fan of limiting `printWidth`and endorse people providing their own config instead,

**Comment by pmdevita** [comment]
In that case, do you think there should be an option to disable Prettier? My thoughts are that since the user isn't necessarily outputting a pure HTML document, processing it like one might cause other issues too.

**Comment by idleberg** [comment]
I now remember that I have chosen prettier formatting as a default to get fix the indentation-issues after manipulating HTML input. But I still agree that there should be an option to turn it off.

I'm planning to update the adapter further in the next couple of days, so stay tuned.
