### ISSUE TITLE
writeStatic has been removed.

### ISSUE THREAD

**Issue by emirhangumus** [idleberg/sveltekit-adapter-html-like#4]
I'm getting this error when try `npm run build`
`Error: writeStatic has been removed. Please ensure you are using the latest version of sveltekit-adapter-html-like`

`svelte.config.js`

`     import preprocess from "svelte-preprocess";
      import adapter from "sveltekit-adapter-html-like"; `
  
      /** @type {import('@sveltejs/kit').Config} */
      const config = {
	      kit: {
		      adapter: adapter(
			      {
				      fallback: 'index.html',
			      }
		      )
	      },
	      preprocess: [
		      preprocess({
			      postcss: true,
		      }),
	      ],
      };
      
      export default config;
`

**Comment by idleberg** [comment]
Unfortunately, the SvelteKit development is still unstable, so I assume that you're using a newer version than this adapter is compatible to. Could you please try installing the latest version on the main branch, e.g. by adding the following your `package.json`:

```json
{
	"devDependencies": {
		"sveltekit-adapter-html-like": "github:idleberg/sveltekit-adapter-html-like#main",	
	}
}
```

**Comment by idleberg** [comment]
According to the [`CHANGELOG`](https://github.com/sveltejs/kit/blob/master/packages/adapter-static/CHANGELOG.md), the `writeStatic` method has been removed in 1.0.0-next.37, so my previous suggestion is likely not helping you might have to use a version prior to that. In the meantime, I will try and update this over the next couple of days.
