### ISSUE TITLE
Missing files in npm build?

### ISSUE THREAD

**Issue by mgomez-tubs** [idleberg/sveltekit-adapter-html-like#6]
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '[...]\node_modules\sveltekit-adapter-html-like\adapter.js' imported from '[...]\node_modules\sveltekit-adapter-html-like\index.js

After checking the files, the adapter.js and platforms.js files are missing. But they are being imported from the index.js file

![image](https://user-images.githubusercontent.com/52193297/208718900-7371b2c4-e976-4f55-8abf-e9bdf9aa2ec2.png)

![image](https://user-images.githubusercontent.com/52193297/208718593-070c6d0b-49c4-4696-a54a-4c3d680b0e0e.png)

**Comment by mgomez-tubs** [comment]
Closing because might be related to me installing it using yarn instead of npm

**Comment by idleberg** [comment]
No, you were right: there were files missing from distribution. Released a small fix, next up is migrating to SvelteKit 1.0!
